<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>SlythOptimizer</AssemblyName>
    <Product>Slyth Optimizer</Product>
    <Version>1.0.0</Version>
    <ApplicationIcon>Assets\slyth.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\slyth.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Slyth.Core\Slyth.Core.csproj" />
  </ItemGroup>

</Project>
